# Build Stage
FROM golang:alpine AS builder
ENV GOTOOLCHAIN=auto

WORKDIR /app

RUN apk add --no-cache git ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN [ -f /app/firebase-service-account.json ] || echo '{}' > /app/firebase-service-account.json

# Build Notification Service binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/bin/notificationservice ./cmd/notificationservice

# Production Stage
FROM alpine:3.19

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Jakarta

COPY --from=builder /app/bin/notificationservice /app/notificationservice
COPY --from=builder /app/firebase-service-account.json /app/firebase-service-account.json

EXPOSE 3001

CMD ["/app/notificationservice"]
