# Build Stage
FROM golang:alpine AS builder
ENV GOTOOLCHAIN=auto

WORKDIR /app

RUN apk add --no-cache git ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build Export Worker binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/bin/exportworker ./cmd/exportworker

# Production Stage
FROM alpine:3.19

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Jakarta

COPY --from=builder /app/bin/exportworker /app/exportworker

# Create exports directory
RUN mkdir -p /app/exports

CMD ["/app/exportworker"]
